-- Example seed data for dog-sns-prototype.
-- Review and replace all demo values before using in production.
-- This inserts two demo stores and store-specific staff members.

with store_seed as (
  select * from (values
    (
      'DEMO_TOKYO',
      'Demo Tokyo Store',
      '今日のわんちゃん 東京店',
      'TOKYO',
      -- Demo PIN: 0000
      -- Use scrypt hashes generated by scripts/create-store-pin-hash.mjs for production stores.
      'sha256:9af15b336e6a9619928537df30b2e6a2376569fcf9d7e773eccede65606529a0',
      'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22600%22 height=%22240%22 viewBox=%220 0 600 240%22%3E%3Crect width=%22600%22 height=%22240%22 rx=%2228%22 fill=%22%23176f62%22/%3E%3Ctext x=%22300%22 y=%22134%22 text-anchor=%22middle%22 font-size=%2252%22 font-family=%22Arial%22 font-weight=%22700%22 fill=%22white%22%3ETokyo Logo%3C/text%3E%3C/svg%3E',
      'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%221270%22 height=%22890%22 viewBox=%220 0 1270 890%22%3E%3Crect x=%2230%22 y=%2230%22 width=%221210%22 height=%22830%22 fill=%22none%22 stroke=%22%23176f62%22 stroke-width=%2218%22/%3E%3Ctext x=%22635%22 y=%22816%22 text-anchor=%22middle%22 font-size=%2248%22 font-family=%22Arial%22 font-weight=%22700%22 fill=%22%23176f62%22%3ETokyo Frame%3C/text%3E%3C/svg%3E',
      '#176f62',
      'default',
      'Asia/Tokyo',
      '今日のわんちゃん 東京店',
      null,
      '#今日のわんちゃん #犬同伴OK #東京店',
      true,
      10,
      'Demo data only. Replace logo_url and frame_url with Supabase Storage public URLs.'
    ),
    (
      'DEMO_KARUIZAWA',
      'Demo Karuizawa Store',
      '今日のわんちゃん 軽井沢店',
      'KARUIZAWA',
      -- Demo PIN: 0000
      -- Use scrypt hashes generated by scripts/create-store-pin-hash.mjs for production stores.
      'sha256:9af15b336e6a9619928537df30b2e6a2376569fcf9d7e773eccede65606529a0',
      'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22600%22 height=%22240%22 viewBox=%220 0 600 240%22%3E%3Crect width=%22600%22 height=%22240%22 rx=%2228%22 fill=%22%236f4a8e%22/%3E%3Ctext x=%22300%22 y=%22134%22 text-anchor=%22middle%22 font-size=%2248%22 font-family=%22Arial%22 font-weight=%22700%22 fill=%22white%22%3EKaruizawa Logo%3C/text%3E%3C/svg%3E',
      'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%221270%22 height=%22890%22 viewBox=%220 0 1270 890%22%3E%3Crect x=%2230%22 y=%2230%22 width=%221210%22 height=%22830%22 fill=%22none%22 stroke=%22%236f4a8e%22 stroke-width=%2218%22/%3E%3Ctext x=%22635%22 y=%22816%22 text-anchor=%22middle%22 font-size=%2248%22 font-family=%22Arial%22 font-weight=%22700%22 fill=%22%236f4a8e%22%3EKaruizawa Frame%3C/text%3E%3C/svg%3E',
      '#6f4a8e',
      'default',
      'Asia/Tokyo',
      '今日のわんちゃん 軽井沢店',
      null,
      '#今日のわんちゃん #犬同伴OK #軽井沢店',
      true,
      20,
      'Demo data only. Replace logo_url and frame_url with Supabase Storage public URLs.'
    )
  ) as stores(
    store_code,
    store_name,
    display_name,
    login_code,
    pin_hash,
    logo_url,
    frame_url,
    theme_color,
    print_template_type,
    timezone,
    sns_display_name,
    instagram_account,
    default_hashtags,
    is_active,
    sort_order,
    notes
  )
), upserted_stores as (
  insert into public.stores (
    store_code,
    store_name,
    display_name,
    login_code,
    pin_hash,
    logo_url,
    frame_url,
    theme_color,
    print_template_type,
    timezone,
    sns_display_name,
    instagram_account,
    default_hashtags,
    is_active,
    sort_order,
    notes
  )
  select
    store_code,
    store_name,
    display_name,
    login_code,
    pin_hash,
    logo_url,
    frame_url,
    theme_color,
    print_template_type,
    timezone,
    sns_display_name,
    instagram_account,
    default_hashtags,
    is_active,
    sort_order,
    notes
  from store_seed
  on conflict (store_code) do update set
    store_name = excluded.store_name,
    display_name = excluded.display_name,
    login_code = excluded.login_code,
    pin_hash = excluded.pin_hash,
    logo_url = excluded.logo_url,
    frame_url = excluded.frame_url,
    theme_color = excluded.theme_color,
    print_template_type = excluded.print_template_type,
    timezone = excluded.timezone,
    sns_display_name = excluded.sns_display_name,
    instagram_account = excluded.instagram_account,
    default_hashtags = excluded.default_hashtags,
    is_active = excluded.is_active,
    sort_order = excluded.sort_order,
    notes = excluded.notes
  returning id, store_code
), staff_seed as (
  select * from (values
    ('DEMO_TOKYO', 'tokyo-manager', '東京 店長', '責任者', true, 10),
    ('DEMO_TOKYO', 'tokyo-hall', '東京 山田', 'ホール', false, 20),
    ('DEMO_TOKYO', 'tokyo-kitchen', '東京 佐藤', 'キッチン', false, 30),
    ('DEMO_KARUIZAWA', 'karuizawa-manager', '軽井沢 店長', '責任者', true, 10),
    ('DEMO_KARUIZAWA', 'karuizawa-hall', '軽井沢 鈴木', 'ホール', false, 20),
    ('DEMO_KARUIZAWA', 'karuizawa-kitchen', '軽井沢 高橋', 'キッチン', false, 30)
  ) as staff(store_code, staff_code, display_name, role_label, can_approve_sns, sort_order)
)
insert into public.staff_members (
  store_id,
  staff_code,
  display_name,
  role_label,
  can_approve_sns,
  is_active,
  sort_order
)
select
  upserted_stores.id,
  staff_seed.staff_code,
  staff_seed.display_name,
  staff_seed.role_label,
  staff_seed.can_approve_sns,
  true,
  staff_seed.sort_order
from upserted_stores
join staff_seed on staff_seed.store_code = upserted_stores.store_code
on conflict (store_id, staff_code) do update set
  display_name = excluded.display_name,
  role_label = excluded.role_label,
  can_approve_sns = excluded.can_approve_sns,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;
